Release v0.1.1 beta.3 (#235)
* tutorial and usage update

* first add

* rm not need

* fix bugs

* add logging

* add docker file

* fix by yancey's comment

* update

* save parameter

* fix yaml

* fix bugs

* fix bugs

* fix convert bug

* fix by wuyi's comment

* add readme

* rm logging.confg

* modify README.md

* modify README.md

* add start command

* update

* update by comments

* upload files with recursion

* prettify output

* remove replica set name

* recursion to loop

* dlnel index page (#194)

* switch to dlnel index page

* mount template files

* delete unused comments

* add port env

* update tutorial (#202)

* update tutorial

* update

* remove unused line

* update

* update

* update

* test format

* modify travis.yaml

* fix

* fix

* fix sudo

* add travis

* add glide

* add gimme

* fix style

* fix style

* add files

* modify sh

* fix by wuyi's comments

* fix pre-commit bugs

* Format quota print (#205)

* forat quota print

* update

* add sleep for pserver get ready (#216)

* Update readme (#214)

* update readme

* update

* Enable ingress notebook access (#219)

* enable ingress notebook access

* update notebook resource

* test ok

* fix

* fix

* fix login url (#229)

* Fix invalid job path (#227)

* fix invalid job path

* update doc

* check job name in clint (#231)

* [Done]Fault tolerant job (#212)

* fault tolerant job

* ft job

* update

* tested job submit with ft job

* update

diff --git a/docker/paddle_k8s b/docker/paddle_k8s
--- a/docker/paddle_k8s
+++ b/docker/paddle_k8s
@@ -11,6 +11,38 @@ start_pserver() {
       --num_gradient_servers=$PADDLE_INIT_NUM_GRADIENT_SERVERS
 }
 
+start_new_pserver() {
+  export MASTER_IP=$(python /root/k8s_tools.py fetch_master_ip)
+  /usr/bin/pserver \
+    -port=$PADDLE_INIT_PORT \
+    -num-pservers=$PSERVERS \
+    -log-level=debug \
+    -etcd-endpoint=http://$PADDLE_INIT_MASTER_IP:2379
+}
+
+start_master() {
+  /usr/bin/master \
+  -port=8080 \
+  -endpoints=http://127.0.0.1:2379
+}
+
+check_trainer_ret() {
+  ret=$1
+  echo "job returned $ret...setting pod return message..."
+  echo "==============================="
+  if [ $ret -eq 136 ] ; then
+    echo "Error Arithmetic Operation(Floating Point Exception)" > /dev/termination-log
+  elif [ $ret -eq 139 ] ; then
+    echo "Segmentation Fault" > /dev/termination-log
+  elif [ $ret -eq 1 ] ; then
+    echo "General Error" > /dev/termination-log
+  elif [ $ret -eq 134 ] ; then
+    echo "Program Abort" > /dev/termination-log
+  fi
+  echo "termination log wroted..."
+  exit $ret
+}
+
 start_trainer() {
     python /root/k8s_tools.py wait_pods_running paddle-job-pserver=${PADDLE_JOB_NAME} ${PSERVERS}
     python /root/k8s_tools.py wait_pods_running paddle-job=${PADDLE_JOB_NAME} ${TRAINERS}
@@ -28,6 +60,10 @@ start_trainer() {
     $PADDLE_INIT_NUM_GRADIENT_SERVERS, "trainer_id: " $PADDLE_INIT_TRAINER_ID, \
     "version: " $1
 
+    # FIXME: If we use the new PServer by Golang, add Kubernetes healthz
+    # to wait PServer process get ready.Now only sleep 20 seconds.
+    sleep 20
+    
     case "$1" in
       "v1")
         paddle train \
@@ -47,9 +83,11 @@ start_trainer() {
           --save_dir=$OUTPUT \
           --pservers=$PADDLE_INIT_PSERVERS \
           --num_gradient_servers=$PADDLE_INIT_NUM_GRADIENT_SERVERS
+        check_trainer_ret $?
         ;;
       "v2")
-        ${ENTRY}
+        sh -c "${ENTRY}"
+        check_trainer_ret $?
         ;;
       *)
         ;;
@@ -68,6 +106,12 @@ case "$1" in
         ;;
     start_trainer)
         start_trainer $2
+        ;;
+    start_new_pserver)
+        start_new_pserver
+        ;;
+    start_master)
+        start_master
         ;;
     --help)
         usage
