update

diff --git a/docker/paddle_k8s b/docker/paddle_k8s
--- a/docker/paddle_k8s
+++ b/docker/paddle_k8s
@@ -26,16 +26,20 @@ start_master() {
   -endpoints=http://127.0.0.1:2379
 }
 
-check_trainer_ret() {
-  ret=$1
-  max_failed=$2
-  stdbuf -oL echo "job returned $ret...setting pod return message..."
-  stdbuf -oL echo "==============================="
-  failed_count=$(python /root/k8s_tools.py count_pods_by_phase paddle-job=${PADDLE_JOB_NAME} Failed)
-  if [ $ret -ne 0 ] && [ $failed_count -gt $max_failed ]; then
-    echo "Failed count beyond the threshold: " $TRAINERS > /dev/termination-log
+check_failed_cnt() {
+  max_failed=$1
+  failed_count=$(python /root/k8s_tools.py count_pods_by_phase paddle-job=${PADDLE_JOB_NAME} Failed) 
+  if [ $failed_count -gt $max_failed ]; then
+    stdbuf -oL echo "Failed trainer count beyond the threadhold: "$max_failed
+    echo "Failed trainer count beyond the threshold: " $max_failed > /dev/termination-log 
     exit 0
   fi
+}
+
+check_trainer_ret() {
+  ret=$1
+  stdbuf -oL echo "job returned $ret...setting pod return message..."
+  stdbuf -oL echo "==============================="
 
   if [ $ret -eq 136 ] ; then
     echo "Error Arithmetic Operation(Floating Point Exception)" > /dev/termination-log
@@ -55,6 +59,9 @@ start_new_trainer() {
   # FIXME: use etcd lock instead of trainer id
   stdbuf -oL python /root/k8s_tools.py wait_pods_running paddle-job=${PADDLE_JOB_NAME} ${TRAINERS} 
 
+  # FIXME(Yancey1989): use command-line interface to configure the max failed count
+  check_failed_cnt 0
+
   export MASTER_IP=$(python /root/k8s_tools.py fetch_master_ip)
   export ETCD_IP="$MASTER_IP"
   export PADDLE_INIT_TRAINER_ID=$(python /root/k8s_tools.py fetch_trainer_id)
@@ -68,13 +75,15 @@ start_new_trainer() {
   "version: " $1 
 
   stdbuf -oL sh -c "${ENTRY}"
-  # FIXME(Yancey1989): use command-line interface to configure the max failed count
-  check_trainer_ret $? ${TRAINERS}
+  check_trainer_ret $?
 }
 
 start_trainer() {
+    check_failed_cnt 0
     stdbuf -oL python /root/k8s_tools.py wait_pods_running paddle-job-pserver=${PADDLE_JOB_NAME} ${PSERVERS}
     stdbuf -oL python /root/k8s_tools.py wait_pods_running paddle-job=${PADDLE_JOB_NAME} ${TRAINERS}
+    # paddle v1 and V2 distributed training does not allow any trainer failed. 
+
     export PADDLE_INIT_PSERVERS=$(python /root/k8s_tools.py fetch_pserver_ips)
     export PADDLE_INIT_TRAINER_ID=$(python /root/k8s_tools.py fetch_trainer_id)
     stdbuf -oL echo $PADDLE_INIT_TRAINER_ID > /trainer_id
@@ -113,12 +122,12 @@ start_trainer() {
           --pservers=$PADDLE_INIT_PSERVERS \
           --num_gradient_servers=$PADDLE_INIT_NUM_GRADIENT_SERVERS
         # paddle v1 API does not allow any trainer failed.
-        check_trainer_ret $? 0
+        check_trainer_ret $? 
         ;;
       "v2")
         stdbuf -oL sh -c "${ENTRY}"
         # paddle v2 API does not allow any trainer failed.
-        check_trainer_ret $? 0
+        check_trainer_ret $? 
         ;;
       *)
         ;;
